config/routes.rb
Beermee::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  match '/auth/:provider/callback' => 'authentications#create'

  resources :ratings,     :only => [:update, :create]
  resources :activities,  :only => [:new, :create, :destroy] do
    get :autocomplete_place_name, :on => :collection
  end
    
  resources :beers do
    get :autocomplete_brewery_name, :on => :collection
    get :autocomplete_beer_name,    :on => :collection
  end 

  resources :breweries
  resources :places
  resources :styles, :only => [:index, :show]
  resources :search, :only => [:index]

  root :to => "pages#home"

end

app/views/shared/_actions.html.haml
#actions.content-box
  .title 
    %h3 
      %strong What are you drinking?
  .box
    = form_for @search, :url => search_index_path, :html => { :method => :get } do |f|
      = f.autocomplete_field :name_contains, autocomplete_beer_name_beers_path 
      = f.submit :class => "search-button", :value => "Search"
    #browse-by
      %h3 Browse by:
      %ul
        %li= link_to "Beers", beers_path
        %li= link_to "Breweries", breweries_path 
        %li= link_to "Style", styles_path

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    %h2
      = pluralize(object.errors.count, "error")
      prohibited this 
      = object.class.to_s.underscore.humanize.downcase
      from being saved:
    %p There were problems with the following fields:
    %ul
    - object.errors.full_messages.each do |msg|
      %li= msg

app/views/shared/_external_auth.html.haml
#external-auth
  %p Sign in with one of these providers:
  %ul#social-icons
    %li= social_icon "facebook", icon_size
    %li= social_icon "twitter", icon_size
  .clear