config/routes.rb
Beermee::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  match '/auth/:provider/callback' => 'authentications#create'

  resources :ratings,     :only => [:update, :create]
  resources :activities,  :only => [:new, :create, :destroy] do
    get :autocomplete_place_name, :on => :collection
  end
    
  resources :beers do
    get :autocomplete_brewery_name, :on => :collection
    get :autocomplete_beer_name,    :on => :collection
  end 

  resources :breweries
  resources :places
  resources :styles, :only => [:index, :show]
  resources :search, :only => [:index]

  root :to => "pages#home"

end

app/models/brewery.rb
# == Schema Information
# Schema version: 20101130052456
#
# Table name: breweries
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  description        :text
#  website            :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :string(255)
#  image_updated_at   :datetime
#

class Brewery < ActiveRecord::Base
  has_many  :beers
  has_many  :activities, :through => :beers, :order => "created_at DESC"
  has_one   :address, :as => :addressable
  accepts_nested_attributes_for :address

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "60x80#" }

  validates :name,        :presence => true, :uniqueness => true
  validates :description, :length   => { :maximum => 1000 }
  validates :website,     :format   => { :with => /^(#{URI::regexp(%w(http https))})$/,
                                         :allow_blank => true }
    
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /breweries
  def index
    if request.format.js?
      @breweries = Brewery.find(:all, 
                              :conditions => ['name LIKE ?', "%#{params[:search]}%"])
    elsif request.format.html?
      @breweries = Brewery.paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js   # index.js.erb
    end
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
    @brewery.build_address.country = Country.find_by_iso3("USA")

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /breweries
  def create
    @brewery = Brewery.new(params[:brewery])
    if @brewery.save
      flash[:notice] = "Brewery successfully added."
      redirect_to breweries_path
    else
      render 'new'
    end
  end

  # GET /breweries/:id
  def show
    @brewery = Brewery.find(params[:id])
    @activities = @brewery.activities
    
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /breweries/:id/edit
  def edit
    @brewery = Brewery.find(params[:id])
    
    @brewery.build_address if @brewery.address.nil?

    respond_to do |format|
      format.html # edit.html.erb
    end
  end

  # PUT /breweries/:id
  def update
    @brewery = Brewery.find(params[:id])
    if @brewery.update_attributes(params[:brewery])
      flash[:notice] = "Brewery updated."
      redirect_to @brewery
    else
      render 'edit'
    end
  end
  
  # DELETE /breweries/:id
  def destroy
    Brewery.find(params[:id]).destroy
    flash[:notice] = "Brewery destroyed."
    redirect_to breweries_path
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_beer_list.html.haml
#breweryBeerList
  = link_to "+ Add", new_beer_path(:brewery_id => @brewery), :class => "add_link"
  %div
    %h2 Beers
    %ul
      - @brewery.beers.each do |beer|
        %li
          .thumb= link_to thumbnail(beer), beer
          = link_to beer.name, beer

app/views/breweries/_brewery.html.haml
%li.brewery-item
  .thumb
    = link_to thumbnail(brewery), brewery
  = link_to "delete", brewery,  :method => :delete, 
                                :confirm => "Are you sure?",
                                :title => "Delete #{brewery.name}", 
                                :class => "delete-link"

  %h3= link_to brewery.name, brewery
  %p
    = brewery.description unless brewery.description.nil?

app/views/breweries/_form.html.haml
= form_for @brewery, :html => { :multipart => true } do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :description
    = f.text_area :description
  = f.fields_for :address do |builder|
    .field
      = builder.label :street, "Address"
      = builder.text_field :street
    .field#city
      = builder.label :city
      = builder.text_field :city
    .field#country
      = builder.label :country
      = builder.select  :country_id, Country.all.collect {|c| [c.name, c.id] }, 
                        :include_blank => true
    .field#state
      = builder.label :state
      = builder.select  :state_id, State.all.collect {|s| [s.name, s.id] }, 
                        :include_blank => true
    .field
      = builder.label :postal_code, "Postal Code"
      = builder.text_field :postal_code
  .field
    = f.label :image
    = f.file_field  :image
  .actions
    = f.submit "Submit"

app/views/breweries/edit.html.haml
= title "Edit Brewery"
%h1.form Edit Brewery
= render 'form'

app/views/breweries/index.html.haml
= title "Breweries"
%h1 Breweries
= link_to "Add a brewery", new_brewery_path, :class => "add-button"
%br
%br
= will_paginate
%ul#brewery-list
  = render @breweries
= will_paginate

app/views/breweries/new.html.haml
= title "Add a brewery"
%h1.form Add a brewery
= render 'form'

app/views/breweries/show.html.haml
= title @brewery.name
- content_for :scripts do
  = javascript_include_tag  'jquery.rating.pack.js', 
                            'jquery.metadata.js',
                            'rating.js'


#show-image.span-6
  = image_tag @brewery.image.url(:medium), :alt => @brewery.name
#show-info.span-12
  #show-title
    %h1= @brewery.name
    = link_to "Edit", edit_brewery_path, :class => "edit_link"

  #info
    - unless @brewery.website.blank?
      %span.label
        %strong Website:
      = link_to @brewery.website, @brewery.website
  #description
    = @brewery.description
#show-actions.span-6.last

= render :partial => 'activities/feed', :locals => { :activities => @activities } unless @activities.nil?
- content_for :aside do
  = render 'beer_list'