config/routes.rb
Beermee::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  match '/auth/:provider/callback' => 'authentications#create'

  resources :ratings,     :only => [:update, :create]
  resources :activities,  :only => [:new, :create, :destroy] do
    get :autocomplete_place_name, :on => :collection
  end
    
  resources :beers do
    get :autocomplete_brewery_name, :on => :collection
    get :autocomplete_beer_name,    :on => :collection
  end 

  resources :breweries
  resources :places
  resources :styles, :only => [:index, :show]
  resources :search, :only => [:index]

  root :to => "pages#home"

end

app/models/beer.rb
# == Schema Information
# Schema version: 20101116221815
#
# Table name: beers
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  brewery_id         :integer
#  description        :text
#  abv                :decimal(, )
#  ibu                :decimal(, )
#  original_gravity   :decimal(, )
#  style_id           :integer
#  website            :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Beer < ActiveRecord::Base
  attr_accessible :name, :style_id, :description, :abv, :ibu, :website,
                  :image, :brewery_name

  has_attached_file :image, 
                    :styles => { :medium => "200x200>", :thumb => "60x80#",
                                 :small => "30x40#" }
  belongs_to :brewery
  belongs_to :style
  has_many  :activities,  :dependent => :destroy
  has_many  :ratings,     :dependent => :destroy


  validates :name,        :presence => true,
                          :length => { :maximum => 50 } 
  validates :description, :length => { :maximum => 1000 }
  validates :abv,         :numericality => { :greater_than_or_equal_to => 0,
                                             :less_than_or_equal_to    => 100,
                                             :allow_nil => true }
  validates :ibu,         :numericality => { :greater_than_or_equal_to => 0,
                                             :less_than_or_equal_to    => 200,
                                             :allow_nil => true }
  validates :style_id,    :presence => true
  validates :website,     :format => { :with => /^(#{URI::regexp(%w(http https))})$/,
                                       :allow_blank => true }


  def average_rating
    value = 0
    total = 0
    ratings.each do |rating| 
      unless rating.new_record? or rating.score.nil?
        value += rating.score 
        total += 1
      end
    end
    total > 0 ? value.to_f / total.to_f : nil   # can't divide by zero
  end

  def rated_by_user?(user)
    !ratings.find_by_user_id(user).nil?
  end

# Virtual attributes
  def brewery_name
    brewery.name if brewery
  end

  def brewery_name=(name)
    self.brewery = Brewery.find_by_name(name) unless name.blank?
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  autocomplete :brewery, :name, :full => true
  autocomplete :beer, :name, :full => true

  # GET /beers
  def index
    @beers = Beer.paginate(:page => params[:page])

    respond_to do |format|
      format.html
    end
  end

  # GET /beers/new
  def new
    @beer = Beer.new

    if params[:brewery_id].nil?
      @brewery_name = ""
    else
      @brewery_name = Brewery.find(params[:brewery_id]).name 
      @beer.brewery_id = params[:brewery_id]
    end

    respond_to do |format|
      format.html
    end
  end

  # POST /beers
  def create
    @beer = Beer.new(params[:beer])
    
    if @beer.save
      flash[:notice] = "Beer successfully added."
      redirect_to beers_path
    else
      render 'new'
    end
  end

  # GET /beers/:id
  def show
    @beer = Beer.find(params[:id])
    if user_signed_in?
      @rating =   @beer.ratings.find_by_user_id(current_user.id)
      @rating ||= @beer.ratings.build(:user_id => current_user.id)
    end

    respond_to do |format| 
      format.html
    end
  end

  # GET /beers/:id/edit
  def edit
    @beer = Beer.find(params[:id])
    @brewery_name = @beer.brewery.name

    respond_to do |format|
      format.html
    end
  end

  # PUT /beers/:id
  def update
    @beer = Beer.find(params[:id])

    if @beer.update_attributes(params[:beer])
      flash[:notice] = "Beer updated."
      redirect_to @beer
    else
      render 'edit'
    end
  end

  # DELETE /beers/:id
  def destroy
    Beer.find(params[:id]).destroy
    flash[:notice] = "Beer destroyed."
    redirect_to beers_path
  end
end

app/helpers/beers_helper.rb
module BeersHelper

  def beer_link(beer)
    link_to beer.name, beer
  end

  def beer_styles
    Style.find(:all).sort! do |a,b| 
      a.name.downcase <=> b.name.downcase
    end.collect { |c| [c.name, c.id] } 
  end
end

app/views/beers/_beer.html.haml
%li.beer-item
  .thumb
    = link_to thumbnail(beer), beer
  %span.beer-brewery
    = link_to beer.brewery.name, beer.brewery
  %span.rating
    %form
      = star_rating( :readonly => true, :rating => beer.average_rating )
  = link_to "delete", beer, :method => :delete, 
                            :confirm => "Are you sure?",
                            :title => "Delete #{beer.name}", 
                            :class => "delete-link"
  %h3
    = link_to beer.name, beer
  %p
    = beer.description unless beer.description.blank?

app/views/beers/_form.html.haml
= form_for @beer, :html => { :multipart => true }  do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :style_id
    = select("beer", "style_id", beer_styles, :include_blank => true)
  .field
    = f.label :brewery_name, "Brewery"
    = f.autocomplete_field :brewery_name, autocomplete_brewery_name_beers_path
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :abv, "ABV"
    = f.text_field :abv
  .field
    = f.label :ibu, "IBUs"
    = f.text_field :ibu
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit "Submit"

app/views/beers/edit.html.haml
= title "Edit beer"
%h1.form Edit Beer
= render 'form'

app/views/beers/index.html.haml
= title "Beers"
%h1 Beers
= link_to "Add a beer", new_beer_path, :class => "add-button"
%br
= will_paginate
%ul#beer-list
  = render @beers
= will_paginate

app/views/beers/new.html.haml
= title "Add a beer"
%h1.form Add a beer
= render 'form'

app/views/beers/show.html.haml
= title "#{@beer.name} | #{@beer.brewery.name}"
#show-image.span-4
  = image_tag @beer.image.url(:medium), :alt => @beer.name
#show-info.span-12
  #show-title
    %h1= @beer.name
    = link_to "Edit", edit_beer_path, :class => "edit_link"
  #average-rating
    = star_rating :readonly => true, :rating => @beer.average_rating
  #info
    %p
      %span.label
        %strong Brewed by:
      = link_to @beer.brewery.name, brewery_path(@beer.brewery)
    %p
      %span.label
        %strong Style:
      = link_to @beer.style.name, style_path(@beer.style)

    - unless @beer.abv.blank?
      %p
        %span.label
          %strong ABV:
        = "#{@beer.abv} %"
    - unless @beer.ibu.blank?
      %p
        %span.label
          %strong IBUs:
        = @beer.ibu
    - unless @beer.original_gravity.blank?
      %p
        %span.label
          %strong>OG:
        = @beer.original_gravity
  #description
    = @beer.description
#show-actions.span-8.last
  - if user_signed_in?
    #user-options
      = link_to "I'm drinking this", new_activity_path(:beer => @beer)
      = render "ratings/star_form"



= render  :partial => "activities/feed", 
          :locals => { :activities => @beer.activities }

- content_for :aside do
  .side-box
    .title
      %h4
        %strong Photos
    .box
      filler filler
  .side-box
    .title
      %h4
        %strong Similar Beers
    .box
      filler filler