config/routes.rb
Beermee::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  match '/auth/:provider/callback' => 'authentications#create'

  resources :ratings,     :only => [:update, :create]
  resources :activities,  :only => [:new, :create, :destroy] do
    get :autocomplete_place_name, :on => :collection
  end
    
  resources :beers do
    get :autocomplete_brewery_name, :on => :collection
    get :autocomplete_beer_name,    :on => :collection
  end 

  resources :breweries
  resources :places
  resources :styles, :only => [:index, :show]
  resources :search, :only => [:index]

  root :to => "pages#home"

end

app/views/layouts/_footer.html.haml
%footer
  %nav.prepend-top
    %ul
      %li= link_to("About", "#")
      %li= link_to("Blog", "#")
      %li= link_to("API", "#")
      %li= link_to("Contact", "#")
      %li#last-footer= link_to("Support", "#")

app/views/layouts/_header.html.haml
%header
  #header-container
    = link_to logo, root_path
    %nav.prepend-top
      %ul
        %li= link_to "Settings", "#"
        %li= link_to "Help", "#"
        %li= link_to "About", "#"
        - if user_signed_in?
          %li= link_to "Sign out", destroy_user_session_path
        - else
          %li= link_to "Sign in", new_user_session_path

app/views/layouts/_nav.html.haml
%nav#sitenav
  %ul
    %li= link_to('Beers', beers_path)
    %li= link_to('Breweries', breweries_path)
    %li.usernav= link_to('Beer Log', '#')
    %li.usernav= link_to('Favorites', '#')
    %li.usernav= link_to('Cellar', '#')

app/views/layouts/_sidebar.html.haml
%nav#sidenav
  %ul
    %li= link_to('Beers', beers_path)
    %li= link_to('Breweries', breweries_path)
    %li= link_to('Places', places_path)
    %li.usernav= link_to('Beer Log', '#')
    %li.usernav= link_to('Favorites', '#')
    %li.usernav= link_to('Cellar', '#')

app/views/layouts/_stylesheets.html.haml
/[if lt IE 9]
  %script{ :src => 'http://html5shiv.googlecode.com/svn/trunk/html5.js' }
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'blueprint/ie'
= stylesheet_link_tag 'jquery-ui-1.8.8.custom.css'
= stylesheet_link_tag 'jquery.rating.css'
= stylesheet_link_tag 'main.css'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      BeerMee -
      = yield :title
    = render 'layouts/stylesheets'
    = javascript_include_tag  'jquery-1.4.4.min.js',
                              'jquery-ui-1.8.8.custom.min.js',
                              'rails.js',
                              'application.js',
                              'autocomplete-rails.js',
                              'jquery.rating.pack.js', 
                              'jquery.metadata.js',
                              'rating.js'

    = yield :scripts
    = csrf_meta_tag
  %body
    = render 'layouts/header'
    .container
      %hr.space
      #top.span-24.prepend-top.append-bottom
        - if flash[:notice]
          %p.notice= notice
        - elsif flash[:alert]
          %p.alert= alert
        = yield 
      %hr
      #feed.span-15.prepend-top
        = yield :feed
      #aside.push-1.span-8.prepend-top.last
        = yield :aside
      %hr.space
    = render 'layouts/footer'